# Generated by Django 3.0.3 on 2020-03-10 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('College_Name', models.CharField(max_length=200)),
                ('College_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Department', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('Student_Name', models.CharField(max_length=60)),
                ('Enrollment_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Dob', models.DateTimeField()),
                ('Cgpa', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('College_Name', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.College')),
            ],
        ),
    ]
